[google_credentials]
type = "service_account"
project_id = "elemental-vent-440006-v2"
private_key_id = "9fe7e94ad369dc44268123a38a8c0a3dd1306042"
private_key = '''
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDCos9wdolabz7v
p1uVFyNZdcI6lHjx/vgVwjfuDu+Kd9VhDlYoibt7XInhrR9W6v6as7niFiPgVVtT
6fX1qZ/P9ek1N29ZxeJUlX+nGFdqD5QKtJSPpLtgs28lmMjT5Ccx6a17QpzX3GNz
svFK7jNNAvgBDtvNhASCWkMlMk2Z3SuhqCmfoDJQ6T1B0ymDe4SO0P8Y/Yv2Hjwe
Dulu/vFchoYfFo/bVRi8jIPU+8XzaScuuuXE2gMfKga8gZ6ieuZcHeLHVqG8GLXJ
hTTmJ9eQpX2CHFw1tCZLlApYZxqCYLTunk9GQcD4XkgEYx8JI2fjHBGuIpbNech3
DILH/Hu/AgMBAAECggEADBEJ6UAADfI9pZ/rhpezolUxoG4Z/W7ANKEg1IpqgVwi
h2zbHJJFZEV9atdPzRSuiirASGr0+HByRAaKMBu/A6aMObdhGOCywmmuS06wBKxI
kk1VtH4S+9DEAEGzmadYYrjI/45GqP9Jzx915B5WYdzgQTiJmfkoSmiMJx8yPmqj
HzkJ9Gwj6/ptwQ91S6T5sbENYxJzHrVhnuH6/8VnIt1oclRCHrMLyDsd+2BBxTBJ
ynD+YZtLWUBDx6M7Werr5hxnPUD+t+M6Qfk3uDwnDw3Dk+8BRMxOJ5jPinI+JtpM
t2+UT3w9YRuzHy0Xkl26+t9JxbbXndtbwwB7xLpo0QKBgQDgsY++dIod3od0rrEI
kdfua+NkFgbL+rHr53FjPnnMtfbDhO78DfrDdjChe+nKKJlHmAytt9x7UniP3krv
WCOpKGrtcvv8wQ+dXsygIGqIp7BR7RfbKGCLkQY+qox3DQB3ppu0PDil+V3a/mvN
s8t2RWiTpa2stuV2QXuVB1oxiQKBgQDdwSUCS2c2RkEpk185QiVMP91YNzUdidoN
SFh5qqqjd9av58xwpYWGp8ZqqlXFQzdFLIa5bjtH4B+5ycxkPSeuC+wVjEpDpCbD
R+kt6lrfLzjtOT3kLOuU8CzxuDNxC99qeXPYqBZIVvSQ4emI8LOI/EI6HFQRC75f
CkOyIkjZBwKBgCb9KKA3wK+mKYMJvRZrmDh66B455DwI6E6y/m3mLWRkPsl2i7GZ
C2ZXX+Dli4/Us6REsg6C1PNhQCJWxFH7zVRQ+xzw0uDs7zSzenZeqZ3E20ecCIOy
4e3V4GuHVJBj5Szd8C66NGo4dxzFARfUlv2S1a6pFRXfNrnqavNVL0VhAoGBAI0A
609yMsbIFVciZkI6VQ0O7ufQ8u09YnFftyJl6urWoKRpeA2IskbVF81rUe6Etvg9
P81Y0kj5sjKoplZ2rGx3GD77XZ11G1DAwPx5MB8KH+B3rWsRRRsHPQzWW59eNUm2
wHrbJpAI+qnFfIGezAomnNXmfW35UauNE06JjlixAoGBAOBwFhbxkM4rZie3Fwp4
kiZk8npuJbIHy0yHJNeMMj1GW4rPKVzdOHRAQx6DvcM9FwrAgQFkVITobrs0QzgS
LOLJeKjl8F8tJXqzNNrZmPKHLR9Ln5EqCE0BgQlwkcB6Nnvv9OpV2jEsb/N257FO
8TQoS1OdDbiGjTbcHjI/z4T1
-----END PRIVATE KEY-----
'''
client_email = "calendarservice@elemental-vent-440006-v2.iam.gserviceaccount.com"
client_id = "115197500379950914609"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/calendarservice%40elemental-vent-440006-v2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# Optional: Add calendar ID if using a shared calendar
# [other_secrets]
# CALENDAR_ID = "your-calendar-id@group.calendar.google.com"